public class Calculator {
    
    public integer x=20,y=10;
    
    public void add(){
        system.debug('sum of' +x+ 'and' +y+ '='  +(x+y));
    }
     public void sub(){
        system.debug('sub of' +x+ 'and' +y+ '='  +(x-y));
    }
     public void mul(){
        system.debug('mul of' +x+ 'and' +y+ '='  +(x*y));
    }
     public void div(){
        system.debug('div of' +x+ 'and' +y+ '='  +(x/y));
    }

}