/********************************************************************
 * Class Name: Employee
 * Created by: kishore v
 * Created on: 3/12/22
 * use of Class: To intialize Employee variables when object of this class created
 * ***************************************************************/
public class Employeess{
    
    public integer empId;
    public string name,position;
    public decimal salary;
   
        public Employeess(integer empId,string position,string name,decimal salary){
        this.empId=empId;
        this.name=name;
        this.position=position;
        this.salary=salary;
        
    }
       }